const { contextBridge, ipcRenderer, webUtils } = require("electron");

const listen = (channel) => (cb) => {
  const wrapped = (_e, payload) => cb(payload);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
};

contextBridge.exposeInMainWorld("halo", {
  checkAppUpdate: () => ipcRenderer.invoke('halo:check-app-update'),
  appUpdateState: () => ipcRenderer.invoke('halo:app-update-state'),
  downloadAppUpdate: () => ipcRenderer.invoke('halo:download-app-update'),
  onAppUpdate: listen('halo:app-update'),
  onWebsiteZoom: listen('halo:website-zoom'),
  serverNewSession: (id) => ipcRenderer.invoke("halo:server-new-session", id),
  serverPreview: (id, item) => ipcRenderer.invoke("halo:server-preview", id, item),
  serverPorts: (id) => ipcRenderer.invoke("halo:server-ports", id),
  serverLatencies: (force = false) => ipcRenderer.invoke("halo:server-latencies", force),
  serverLatency: (id) => ipcRenderer.invoke("halo:server-latency", id),
  serverList: () => ipcRenderer.invoke("halo:server-list"),
  serverReorder: (ids) => ipcRenderer.invoke("halo:server-reorder", ids),
  serverSave: (input) => ipcRenderer.invoke("halo:server-save", input),
  serverSelect: (id) => ipcRenderer.invoke("halo:server-select", id),
  serverRemove: (id) => ipcRenderer.invoke("halo:server-remove", id),
  // state / session
  getState: () => ipcRenderer.invoke("halo:get-state"),
  environmentStatus: () => ipcRenderer.invoke('halo:environment-status'),
  environmentInstall: () => ipcRenderer.invoke('halo:environment-install'),
  onEnvironmentProgress: listen('halo:environment-progress'),
  videoSettings: () => ipcRenderer.invoke('halo:video-settings'),
  videoBalance: input => ipcRenderer.invoke('halo:video-balance', input),
  videoHistory: () => ipcRenderer.invoke('halo:video-history'),
  environmentRepair: () => ipcRenderer.invoke('halo:environment-repair'),
  githubStatus: () => ipcRenderer.invoke('halo:github-status'),
  cloudflareStatus: () => ipcRenderer.invoke('halo:cloudflare-status'),
  cloudflareLogin: () => ipcRenderer.invoke('halo:cloudflare-login'),
  cloudflareLogout: () => ipcRenderer.invoke('halo:cloudflare-logout'),
  githubLogin: () => ipcRenderer.invoke('halo:github-login'),
  githubLogout: account => ipcRenderer.invoke('halo:github-logout', account),
  environmentRepairStop: () => ipcRenderer.invoke('halo:environment-repair-stop'),
  onEnvironmentRepairProgress: listen('halo:environment-repair-progress'),
  videoSave: input => ipcRenderer.invoke('halo:video-save', input),
  videoTest: input => ipcRenderer.invoke('halo:video-test', input),
  videoEstimate: input => ipcRenderer.invoke('halo:video-estimate', input),
  videoModelPrices: input => ipcRenderer.invoke('halo:video-model-prices', input),
  init: (cwd) => ipcRenderer.invoke("halo:init", cwd),
  prompt: (text, opts) => ipcRenderer.invoke("halo:prompt", text, opts),
  steer: (text) => ipcRenderer.invoke("halo:steer", text),
  followUp: (text) => ipcRenderer.invoke("halo:followUp", text),
  abort: () => ipcRenderer.invoke("halo:abort"),
  compact: (instructions) => ipcRenderer.invoke("halo:compact", instructions),
  listModels: () => ipcRenderer.invoke("halo:list-models"),
  defaultModelGet: () => ipcRenderer.invoke("halo:default-model-get"),
  defaultModelSet: (key) => ipcRenderer.invoke("halo:default-model-set", { key }),
  setModel: (provider, id) => ipcRenderer.invoke("halo:set-model", provider, id),
  setThinking: (level) => ipcRenderer.invoke("halo:set-thinking", level),
  listSessions: () => ipcRenderer.invoke("halo:list-sessions"),
  usageSummary: (days) => ipcRenderer.invoke("halo:usage-summary", { days }),
  modelQuota: (provider, force) => ipcRenderer.invoke("halo:model-quota", provider, force),
  openSession: (file) => ipcRenderer.invoke("halo:open-session", file),
  newSession: () => ipcRenderer.invoke("halo:new-session"),
  deleteSession: (file) => ipcRenderer.invoke("halo:delete-session", file),
  createEntry: (opts) => ipcRenderer.invoke("halo:create-entry", opts),
  deleteEntry: (target) => ipcRenderer.invoke("halo:delete-entry", { target }),
  previewTouch: (on) => ipcRenderer.invoke("halo:preview-touch", { on }),
  snapshotMessages: () => ipcRenderer.invoke("halo:snapshot-messages"),
  snapshotView: () => ipcRenderer.invoke("halo:snapshot-view"),
  listResources: () => ipcRenderer.invoke("halo:list-resources"),

  // auth / login（与 pi CLI 共享认证）
  authProviders: () => ipcRenderer.invoke("halo:auth-providers"),
  authLogin: (providerId, type) => ipcRenderer.invoke("halo:auth-login", providerId, type),
  authRespond: (value) => ipcRenderer.invoke("halo:auth-respond", value),
  authCancel: () => ipcRenderer.invoke("halo:auth-cancel"),
  authLogout: (providerId) => ipcRenderer.invoke("halo:auth-logout", providerId),
  // 多账户（订阅登录身份保管库 + 一键切换）
  authAccountCapture: (providerId, label) => ipcRenderer.invoke("halo:auth-account-capture", providerId, label),
  authAccountSwitch: (providerId, accountId) => ipcRenderer.invoke("halo:auth-account-switch", providerId, accountId),
  authAccountRemove: (providerId, accountId) => ipcRenderer.invoke("halo:auth-account-remove", providerId, accountId),
  authAccountRename: (providerId, accountId, label) => ipcRenderer.invoke("halo:auth-account-rename", providerId, accountId, label),
  authAccountQuotas: (providerId) => ipcRenderer.invoke("halo:auth-account-quotas", providerId),
  extToggle: (extPath, enabled) => ipcRenderer.invoke("halo:ext-toggle", extPath, enabled),

  // dialogs
  pickProject: (current) => ipcRenderer.invoke("halo:pick-project", current),
  useProject: (dir) => ipcRenderer.invoke("halo:use-project", dir),
  pkgSearch: (q) => ipcRenderer.invoke("halo:pkg-search", q),
  pkgInstalled: () => ipcRenderer.invoke("halo:pkg-installed"),
  pkgInstall: (source) => ipcRenderer.invoke("halo:pkg-install", { source }),
  pkgRemove: (source) => ipcRenderer.invoke("halo:pkg-remove", { source }),
  pkgUpdate: (source) => ipcRenderer.invoke("halo:pkg-update", { source }),
  pkgUpdateAll: () => ipcRenderer.invoke("halo:pkg-update-all"),
  pkgToggle: (raw, on) => ipcRenderer.invoke("halo:pkg-toggle", { raw, on }),
  pkgReload: () => ipcRenderer.invoke("halo:pkg-reload"),
  agentList: () => ipcRenderer.invoke("halo:agent-list"),
  projectsList: () => ipcRenderer.invoke("halo:projects-list"),
  projectSwitch: (cwd) => ipcRenderer.invoke("halo:project-switch", { cwd }),
  droppedFilePath: (file) => webUtils.getPathForFile(file),
  projectAdd: (dir) => ipcRenderer.invoke("halo:project-add", { dir }),
  projectRemove: (cwd) => ipcRenderer.invoke("halo:project-remove", { cwd }),
  agentDefaultGet: () => ipcRenderer.invoke("halo:agent-default-get"),
  agentDefaultSet: (name) => ipcRenderer.invoke("halo:agent-default-set", { name }),
  pickImages: () => ipcRenderer.invoke("halo:pick-images"),

  // workspace / preview
  readTree: () => ipcRenderer.invoke("halo:read-tree"),
  documentPreview: (file, page) => ipcRenderer.invoke("halo:document-preview", { file, page }),
  copyImage: (file) => ipcRenderer.invoke("halo:copy-image", file),
  artifactFiles: (files) => ipcRenderer.invoke("halo:artifact-files", files),
  readFile: (p) => ipcRenderer.invoke("halo:read-file", p),
  openPath: (p) => ipcRenderer.invoke("halo:open-path", p),
  openExternal: (url) => ipcRenderer.invoke("halo:open-external", url),
  ptyStart: (opts) => ipcRenderer.invoke("halo:pty-start", opts),
  ptyWrite: (data) => ipcRenderer.invoke("halo:pty-write", data),
  ptyKill: (id) => ipcRenderer.invoke("halo:pty-kill", id),
  ptyResize: (data) => ipcRenderer.invoke("halo:pty-resize", data),
  ptyAck: (data) => ipcRenderer.invoke("halo:pty-ack", data),
  onPtyOut: listen("halo:pty-out"),
  onPtyExit: listen("halo:pty-exit"),

  // window
  minimize: () => ipcRenderer.send("win:minimize"),
  maximize: () => ipcRenderer.send("win:maximize"),
  close: () => ipcRenderer.send("win:close"),

  // events from main
  onState: listen("halo:state"),
  onPiEvent: listen("pi:event"),
  onError: listen("halo:error"),
  onWinState: listen("halo:winstate"),
  onWindowShown: listen("halo:window-shown"),
  onTreeChanged: listen("halo:tree-changed"),

  // splash -> main
  splashDone: () => ipcRenderer.invoke("halo:splash-done"),
  startupState: () => ipcRenderer.invoke('halo:startup-state'),
  onStartupProgress: listen('halo:startup-progress'),
  rendererReady: () => ipcRenderer.invoke('halo:renderer-ready'),
  rendererFailed: error => ipcRenderer.invoke('halo:renderer-failed', error),
  startupRetry: () => ipcRenderer.invoke('halo:startup-retry'),
  workspaceReady: error => ipcRenderer.invoke('halo:workspace-ready', error),
});
