/**
 * Pi Halo — Electron main process
 * splash (launch animation) -> main window (three-panel celestial console)
 */

import { app, BrowserWindow, ipcMain, dialog, shell, protocol, safeStorage } from "electron";
import path from "node:path";
import fs from "node:fs";
import { spawn } from "node:child_process";
import iconv from "iconv-lite";
import { fileURLToPath } from "node:url";
import { PiBridge, HaloStore, scanAgents } from "./pi-bridge.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.join(HERE, "..", "..");
const PRELOAD = path.join(DIST, "src", "preload", "preload.cjs");
const ICON = path.join(DIST, "assets", "icon.png");

/* 统一限额/常量（调参只改这里） */
const LIMITS = {
  TREE_CAP: 1200,        // 文件树最多条目
  TREE_DEPTH: 8,         // 文件树最大深度
  FILE_READ: 512 * 1024, // 单文件读取上限
  PREVIEW: 8 * 1024 * 1024,  // 预览协议单文件上限
  IMAGE_PICK: 25 * 1024 * 1024, // 附加图片单张上限
  EARLY_EVENTS: 500,     // 主窗口就绪前的事件缓冲
  TREE_WATCH_DEBOUNCE: 600, // 文件树 watcher 防抖
  PKG_TIMEOUT: 180000,   // pi CLI 子进程超时
};

/* 路径归一化：Windows 反斜杠 → 正斜杠、去尾斜杠、小写（仅用于比较） */
const normP = (p) => String(p || "").replace(/\\/g, "/").replace(/\/$/, "").toLowerCase();

/* 凭据保管库加密（Windows DPAPI / macOS Keychain，不可用时回退明文） */
const seal = (s) => {
  try {
    if (safeStorage?.isEncryptionAvailable?.()) return safeStorage.encryptString(s).toString("base64");
  } catch {}
  return null;
};
const unseal = (s) => {
  try {
    if (safeStorage?.isEncryptionAvailable?.()) return safeStorage.decryptString(Buffer.from(s, "base64"));
  } catch {}
  return null;
};

/* 预览注入脚本（独立文件，便于 lint / 语法检查） */
const readInject = (name) => fs.readFileSync(path.join(HERE, "inject", name), "utf8");
const TOUCH_ON = readInject("touch-on.js");
const TOUCH_OFF = readInject("touch-off.js");
const SCROLL_STYLE = readInject("scroll-style.js");

/* pi SDK 会随会话运行时/扩展环境注册一组关闭钩子（SIGINT/SIGTERM/beforeExit），
 * 重建几次后数量超过 Node 默认上限 10，触发“内存泄漏”误报。
 * 这些钩子是 SDK 的正常清理逻辑，并非泄漏 —— 这里取消上限以消除噪音。 */
process.setMaxListeners?.(0);

// privileged scheme so the Preview pane can load workspace files in an iframe
protocol.registerSchemesAsPrivileged([
  { scheme: "halo-preview", privileges: { standard: true, secure: true, supportFetchAPI: true, stream: true } },
]);

app.setName("Pi Halo");

let splashWin = null;
let mainWin = null;
let quitting = false;

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  // 已有实例在跑：干净退出（exit 0），避免 npm start 报 “exited with code 127”；
  // first 实例会收到 second-instance 事件并聚焦已有窗口
  app.exit(0);
} else {
  bootstrap();
}

/* 生成默认智能体注入扩展：每次 agent 启动前实时读 halo-settings.json，把选中智能体的提示追加到系统提示 */
/* 生成默认智能体注入扩展：每次 agent 启动前实时读 halo-settings.json，把选中智能体的提示追加到系统提示。
 * 实际 handler 在 pi-bridge 的 extensionsOverride 内联实现；这里只写一个最小存根文件
 * （loader 需要 path 指向真实存在的文件），避免双份维护扫描逻辑。 */
/* 生成默认智能体注入扩展：每次 agent 启动前实时读 halo-settings.json，把选中智能体的提示追加到系统提示。
 * 实际 handler 在 pi-bridge 的 extensionsOverride 内联实现；这里只写一个最小存根文件
 * （loader 需要 path 指向真实存在的文件），避免双份维护扫描逻辑。 */
function writeAgentExt(storeFile) {
  const file = path.join(path.dirname(storeFile), "halo-default-agent-ext.mjs");
  const code = "/* Generated by Pi Halo — default agent injection. Do not edit. */\nexport default function () {};\n";
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, code);
  } catch (e) {
    console.error("[halo] write agent ext failed:", e);
  }
  return file;
}

function bootstrap() {
  const store = new HaloStore(path.join(app.getPath("userData"), "halo-settings.json"));
  const bridge = new PiBridge(store, { seal, unseal });

  // 生成默认智能体注入扩展（每次启动重写，路径/配置指向最新）
  writeAgentExt(store.file);

  /* 主窗口创建前（splash 预热期）的 pi:event 先入环形缓冲，窗口就绪后重放，避免事件丢失 */
  const pendingEvents = [];
  const emit = (channel, payload) => {
    if (mainWin && !mainWin.isDestroyed()) { mainWin.webContents.send(channel, payload); return; }
    if (channel === "pi:event") {
      pendingEvents.push({ channel, payload });
      if (pendingEvents.length > LIMITS.EARLY_EVENTS) pendingEvents.shift();
    }
  };
  const flushPendingEvents = () => {
    while (pendingEvents.length) {
      const { channel, payload } = pendingEvents.shift();
      mainWin?.webContents.send(channel, payload);
    }
  };
  bridge.onEvent(emit);

  /* ---------------- splash ---------------- */

  function createSplash() {
    splashWin = new BrowserWindow({
      width: 640,
      height: 420,
      icon: ICON,
      frame: false,
      transparent: true,
      resizable: false,
      movable: false,
      skipTaskbar: true,
      alwaysOnTop: true,
      show: false,
      backgroundColor: "#00000000",
      webPreferences: {
        preload: PRELOAD,
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true,
      },
    });
    splashWin.loadFile(path.join(DIST, "src", "renderer", "splash.html"));
    splashWin.once("ready-to-show", () => {
      splashWin.center();
      splashWin.show();
      splashWin.focus();
    });

    // start warming the agent core while the animation plays
    const startCwd = store.data.cwd || path.join(app.getPath("home"), "Desktop");
    bridge.start(startCwd).catch((e) => {
      console.error("[halo] bridge start failed:", e);
      emit("halo:error", { message: String(e?.message || e) });
    });

    // safety: never let splash block the app
    setTimeout(() => finishSplash(), 7000);
  }

  function finishSplash() {
    if (!splashWin || splashWin.isDestroyed()) return;
    createMainWindow();
    splashWin.close();
    splashWin = null;
  }

  /* ---------------- main window ---------------- */

  function createMainWindow() {
    mainWin = new BrowserWindow({
      width: 1440,
      height: 900,
      minWidth: 1120,
      minHeight: 720,
      icon: ICON,
      frame: false,
      show: false,
      backgroundColor: "#0b0b0c",
      titleBarStyle: "hidden",
      webPreferences: {
        preload: PRELOAD,
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true,
        spellcheck: false,
      },
    });

    mainWin.loadFile(path.join(DIST, "src", "renderer", "index.html"));
    mainWin.once("ready-to-show", () => {
      mainWin.show();
      mainWin.focus();
      emit("halo:window-shown", {});
      flushPendingEvents(); // 重放 splash 预热期缓冲的 pi 事件
    });
    mainWin.on("maximize", () => emit("halo:winstate", { maximized: true }));
    mainWin.on("unmaximize", () => emit("halo:winstate", { maximized: false }));
    mainWin.on("closed", () => (mainWin = null));
    mainWin.on("close", () => {
      if (!quitting) {
        quitting = true;
        disarmTreeWatcher();
        bridge.dispose();
      }
    });
    // open external links in browser（只放行 https，其余一律拒绝）
    mainWin.webContents.setWindowOpenHandler(({ url }) => {
      if (/^https?:\/\//.test(url)) shell.openExternal(url);
      return { action: "deny" };
    });
  }

  /* ---------------- IPC ---------------- */

  // 预览触摸模拟：平板/手机模式隐藏滚动条 + 按住拖动滚动 + 松手惯性 + 拖动后抑制误点击
  let previewTouch = false;
  /* 预览触摸模拟 / 滚动条美化脚本：独立文件注入（src/main/inject/），
   * 平板/手机模式隐藏滚动条 + 按住拖动滚动 + 松手惯性 + 拖动后抑制误点击 */
  const applyPreviewTouch = (attempt = 0) => {
    const frames = (() => {
      try { return mainWin?.webContents.mainFrame.frames || []; } catch { return []; }
    })();
    const hits = frames.filter((f) => String(f.url).startsWith("halo-preview://"));
    if (!hits.length) {
      // iframe 可能尚未挂载，重试几次；关闭开关时无需重试
      if (previewTouch && attempt < 6) setTimeout(() => applyPreviewTouch(attempt + 1), 250);
      return;
    }
    for (const f of hits) {
      Promise.resolve(f.executeJavaScript(SCROLL_STYLE)).catch(() => {});
      Promise.resolve(f.executeJavaScript(previewTouch ? TOUCH_ON : TOUCH_OFF)).catch(() => {});
    }
  };

  const handle = (channel, fn) => {
    ipcMain.handle(channel, async (e, ...args) => {
      try {
        return { ok: true, data: await fn(...args) };
      } catch (err) {
        return { ok: false, error: String(err?.message || err) };
      }
    });
  };

  handle("halo:splash-done", async () => {
    // give the main window a beat to paint before splash fades
    setTimeout(() => finishSplash(), 350);
    return true;
  });

  handle("halo:get-state", () => bridge.publicState());
  handle("halo:init", (cwd) => bridge.start(cwd));
  handle("halo:prompt", (text, opts) => bridge.prompt(text, opts));
  handle("halo:steer", (text) => bridge.steer(text));
  handle("halo:followUp", (text) => bridge.followUp(text));
  handle("halo:abort", () => bridge.abort());
  handle("halo:compact", (instructions) => bridge.compact(instructions));
  handle("halo:list-models", () => bridge.listModels());
  handle("halo:default-model-get", async () => store.data.defaultModel || "");
  handle("halo:default-model-set", async ({ key }) => {
    store.set("defaultModel", key || "");
    return true;
  });
  handle("halo:set-model", (provider, id) => bridge.setModel(provider, id));
  handle("halo:set-thinking", (level) => bridge.setThinkingLevel(level));
  handle("halo:list-sessions", () => bridge.listSessions());
  handle("halo:usage-summary", (args) => bridge.usageSummary(args?.days || 30));
  handle("halo:model-quota", (provider, force) => bridge.modelQuota(provider, force));

  // auth / login（与 pi CLI 共享 ~/.pi/agent/auth.json）
  handle("halo:auth-providers", () => bridge.authProviders());
  handle("halo:auth-login", (providerId, type) => bridge.authLogin(providerId, type));
  handle("halo:auth-respond", (value) => bridge.authPromptRespond(value));
  handle("halo:auth-cancel", () => bridge.authCancel());
  handle("halo:auth-logout", (providerId) => bridge.authLogout(providerId));
  // 多账户：保存当前身份 / 一键切换 / 删除 / 重命名
  handle("halo:auth-account-capture", (providerId, label) => bridge.authAccountCapture(providerId, label));
  handle("halo:auth-account-switch", (providerId, accountId) => bridge.authAccountSwitch(providerId, accountId));
  handle("halo:auth-account-remove", (providerId, accountId) => bridge.authAccountRemove(providerId, accountId));
  handle("halo:auth-account-rename", (providerId, accountId, label) => bridge.authAccountRename(providerId, accountId, label));
  handle("halo:auth-account-quotas", (providerId) => bridge.authAccountsQuota(providerId));
  handle("halo:ext-toggle", (extPath, enabled) => bridge.setExtensionEnabled(extPath, enabled));
  handle("halo:open-session", (file) => bridge.openSession(file));
  handle("halo:new-session", () => bridge.newSession());
  handle("halo:delete-session", (file) => bridge.deleteSession(file));
  handle("halo:preview-touch", async ({ on }) => {
    previewTouch = !!on;
    applyPreviewTouch();
    return { on: previewTouch };
  });
  handle("halo:snapshot-messages", () => bridge.snapshotMessages());
  handle("halo:list-resources", () => bridge.listResources());

  /* ---------------- workspace & preview ---------------- */

  const isInsideProject = (p) => {
    const root = path.resolve(bridge.cwd || "");
    const abs = path.resolve(p);
    return abs === root || abs.startsWith(root + path.sep);
  };

  const IGNORE = new Set(["node_modules", ".git", "dist", "build", "out", ".next",
    ".nuxt", ".cache", "coverage", "__pycache__", ".venv", "venv", "target", ".idea"]);
  const IGNORE_SEG = new RegExp("(^|[/\\\\])(" + [...IGNORE].join("|") + ")([/\\\\]|$)");

  /* 文件树 watcher：项目内文件变化（含外部编辑器修改）时通知渲染层刷新；
   * 失败（EPERM 等）时静默降级 —— 渲染层在工具写入后仍会主动刷新 */
  let treeWatcher = null, treeWatchTimer = null;
  const armTreeWatcher = () => {
    try {
      disarmTreeWatcher();
      const root = bridge.cwd || process.cwd();
      treeWatcher = fs.watch(root, { recursive: true }, (_ev, fname) => {
        const n = String(fname || "").replace(/\\\\/g, "/");
        if (!n || IGNORE_SEG.test(n) || n.split("/").some((seg) => seg.startsWith("."))) return;
        clearTimeout(treeWatchTimer);
        treeWatchTimer = setTimeout(() => emit("halo:tree-changed", {}), LIMITS.TREE_WATCH_DEBOUNCE);
      });
    } catch { treeWatcher = null; }
  };
  const disarmTreeWatcher = () => {
    clearTimeout(treeWatchTimer);
    treeWatchTimer = null;
    try { treeWatcher?.close(); } catch {}
    treeWatcher = null;
  };

  handle("halo:read-tree", async () => {
    armTreeWatcher();
    const root = path.resolve(bridge.cwd || ".");
    let count = 0;
    const walk = async (dir, depth) => {
      if (depth > LIMITS.TREE_DEPTH || count > LIMITS.TREE_CAP) return [];
      let entries = [];
      try { entries = await fs.promises.readdir(dir, { withFileTypes: true }); } catch { return []; }
      entries.sort((a, b) => (a.isDirectory() === b.isDirectory())
        ? a.name.localeCompare(b.name)
        : (a.isDirectory() ? -1 : 1));
      const out = [];
      for (const e of entries) {
        if (count > LIMITS.TREE_CAP) break;
        if (IGNORE.has(e.name) || e.name.startsWith(".")) continue;
        const full = path.join(dir, e.name);
        if (e.isDirectory()) {
          count++;
          out.push({ name: e.name, path: full, dir: true, children: await walk(full, depth + 1) });
        } else {
          count++;
          let size = 0;
          try { size = (await fs.promises.stat(full)).size; } catch {}
          out.push({ name: e.name, path: full, dir: false, size });
        }
      }
      return out;
    };
    return { root, tree: await walk(root, 0), truncated: count > LIMITS.TREE_CAP };
  });

  // 新建文件/文件夹（名称校验 + 限定项目内）
  const VALID_NAME = /^[^\\/:*?"<>|]+$/;
  handle("halo:create-entry", async ({ parent, name, kind }) => {
    const root = path.resolve(bridge.cwd || ".");
    const rel = String(name || "").trim();
    if (!rel || rel === "." || rel === ".." || !VALID_NAME.test(rel)) throw new Error("名称非法（不能包含 \\/:*?\"<>|）");
    const base = parent ? path.resolve(parent) : root;
    if (!isInsideProject(base)) throw new Error("路径超出项目范围");
    const target = path.join(base, rel);
    if (fs.existsSync(target)) throw new Error(`已存在：${rel}`);
    if (kind === "dir") fs.mkdirSync(target);
    else fs.writeFileSync(target, "", { flag: "wx" });
    return { path: target };
  });

  // 删除文件/文件夹（递归 + 限定项目内，禁止删除根目录；异步避免阻塞主进程）
  handle("halo:delete-entry", async ({ target }) => {
    const root = path.resolve(bridge.cwd || ".");
    const abs = path.resolve(bridge.cwd || ".", String(target || ""));
    if (abs === root) throw new Error("不能删除项目根目录");
    if (!isInsideProject(abs)) throw new Error("路径超出项目范围");
    if (!fs.existsSync(abs)) throw new Error("目标不存在");
    await fs.promises.rm(abs, { recursive: true });
    return { deleted: abs };
  });

  handle("halo:read-file", async (p) => {
    const abs = path.resolve(bridge.cwd || ".", p);
    if (!isInsideProject(abs)) throw new Error("路径超出项目范围");
    const st = fs.statSync(abs);
    if (st.size > LIMITS.FILE_READ) {
      const fd = fs.openSync(abs, "r");
      const buf = Buffer.alloc(LIMITS.FILE_READ);
      fs.readSync(fd, buf, 0, buf.length, 0);
      fs.closeSync(fd);
      const text = buf.toString("utf8");
      if (text.includes("\0")) throw new Error("二进制文件");
      return { content: text, truncated: true, size: st.size };
    }
    const text = fs.readFileSync(abs, "utf8");
    if (text.includes("\0")) throw new Error("二进制文件");
    return { content: text, truncated: false, size: st.size };
  });

  handle("halo:open-path", async (p) => {
    const abs = path.resolve(bridge.cwd || ".", p);
    if (!isInsideProject(abs)) throw new Error("路径超出项目范围");
    return shell.openPath(abs);
  });

  handle("halo:open-external", (url) => {
    if (!/^https:\/\//.test(String(url))) throw new Error("仅允许 https 链接");
    shell.openExternal(String(url));
    return true;
  });

  /* ------------- 预览区控制台：隐藏控制台 + 管道模式 cmd /Q -------------
   * cmd /Q 不回显；渲染层自绘提示符、本地行编辑、方向键历史、cls 清屏。
   * cmd 的真实提示符（X:\...>）在主进程被吞掉，同时从提示符解析 cwd 推给渲染层；
   * 命令结束信号 = 下一个提示符到达（halo:pty-done）。编码统一 GBK（系统 OEM）。
   */
  let termChild = null, tBuf = "", tAwait = false;
  const TERM_PROMPT_RE = /^([A-Za-z]:\\[^>\r\n]*>)$/;
  handle("halo:pty-start", () => {
    if (termChild) return true;
    const cwd = bridge.cwd || process.cwd();
    termChild = spawn("cmd.exe", ["/Q", "/D", "/C", "chcp 936 >nul & cmd.exe /Q /D /K"], {
      cwd, stdio: ["pipe", "pipe", "pipe"], windowsHide: true,
    });
    tBuf = ""; tAwait = false;
    const send = (ch, payload) => mainWin?.webContents.send(ch, payload);
    /* 行切分 + 提示符识别（feed 接收的是已解码的完整文本流） */
    const feed = (text) => {
      tBuf += text;
      let idx;
      while ((idx = tBuf.search(/\r\n|\n|\r/)) >= 0) {
        const line = tBuf.slice(0, idx);
        tBuf = tBuf.slice(idx + (tBuf[idx] === "\r" && tBuf[idx + 1] === "\n" ? 2 : 1));
        const m = TERM_PROMPT_RE.exec(line);
        if (m) {
          send("halo:pty-cwd", m[1].slice(0, -1));
          if (tAwait) { tAwait = false; send("halo:pty-done"); }
          continue;
        }
        send("halo:pty-out", line + "\r\n");
      }
      if (tBuf) {
        if (TERM_PROMPT_RE.test(tBuf)) { // 无换尾的等待提示符
          const m = TERM_PROMPT_RE.exec(tBuf);
          tBuf = "";
          send("halo:pty-cwd", m[1].slice(0, -1));
          if (tAwait) { tAwait = false; send("halo:pty-done"); }
        } else if (!tAwait) { // 空闲时来的零散字节（进度条等）直接透传
          send("halo:pty-out", tBuf);
          tBuf = "";
        } // 命令执行中：攒整行，防止提示符前缀泄漏
      }
    };
    /* GBK 有状态流式解码：多字节汉字可能被 TCP 分片截断，
     * 按 chunk 独立 decode 会把跨片汉字解成乱码（实测复现），必须用 decodeStream */
    const outDec = iconv.decodeStream("gbk");
    outDec.on("data", (s) => feed(String(s)));
    termChild.stdout.pipe(outDec);
    const errDec = iconv.decodeStream("gbk");
    errDec.on("data", (s) => send("halo:pty-out", String(s).replace(/\r?\n/g, "\r\n")));
    termChild.stderr.pipe(errDec);
    termChild.on("close", () => { termChild = null; tBuf = ""; tAwait = false; send("halo:pty-exit"); });
    return true;
  });
  handle("halo:pty-write", (d) => {
    try {
      const s = String(d);
      if (/\r|\n/.test(s)) tAwait = true; // 提交了一行
      termChild?.stdin.write(iconv.encode(s, "gbk"));
    } catch {}
  });
  handle("halo:pty-kill", () => {
    const c = termChild;
    termChild = null;
    if (c?.pid) { try { spawn("taskkill", ["/PID", String(c.pid), "/T", "/F"], { windowsHide: true }); } catch { try { c.kill(); } catch {} } }
  });

  handle("halo:pick-project", async (currentPath) => {
    const res = await dialog.showOpenDialog(mainWin, {
      title: "选择项目目录",
      defaultPath: currentPath || store.data.cwd || undefined,
      properties: ["openDirectory"],
    });
    if (res.canceled || !res.filePaths[0]) return null;
    const dir = res.filePaths[0];
    // 注意：对话框返回的是原生路径（Windows 带反斜杠），bridge.cwd 已归一化为正斜杠，
    // 必须用 normP 比较，否则“选当前目录”也会误判为切换而重启整个 agent 核心
    if (normP(dir) !== normP(bridge.cwd)) {
      store.set("cwd", dir);
      bridge.cwd = dir;
      await bridge.start(dir);
    }
    return dir;
  });

  /* 静默切换项目（启动恢复工作区用，无对话框） */
  handle("halo:use-project", async (dir) => {
    if (!dir || !fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) throw new Error("目录不存在");
    if (normP(dir) !== normP(bridge.cwd)) {
      store.set("cwd", dir);
      bridge.cwd = dir;
      await bridge.start(dir);
    }
    return true;
  });

  /* ---------------- 插件与技能（pi 包生态） ---------------- */
  const piHome = () => path.join(app.getPath("home"), ".pi", "agent");
  const readPiSettings = () => {
    try { return JSON.parse(fs.readFileSync(path.join(piHome(), "settings.json"), "utf8")); } catch { return {}; }
  };
  const writePiSettings = (obj) => {
    fs.mkdirSync(piHome(), { recursive: true });
    fs.writeFileSync(path.join(piHome(), "settings.json"), JSON.stringify(obj, null, 2) + "\n");
  };
  /* pi CLI 子进程：Windows 用 cmd /d /s /c ""pi.cmd" args"（windowsVerbatimArguments 原样传参，不经 shell:true），
   * 非 Windows 直接 spawn "pi"。所有包源参数均经过 ensureSource 白名单校验（无空格/无 shell 元字符），
   * 即使拼入命令行也不可能逃逸。 */
  const piCommand = () => {
    if (process.platform !== "win32") return "pi";
    const p = process.env.APPDATA ? path.join(process.env.APPDATA, "npm", "pi.cmd") : "";
    return p && fs.existsSync(p) ? p : "pi.cmd";
  };
  const spawnPi = (args) => new Promise((resolve) => {
    const win = process.platform === "win32";
    const child = win
      ? spawn("cmd.exe", ["/d", "/s", "/c", `""${piCommand()}" ${args.join(" ")}"`], { windowsHide: true, windowsVerbatimArguments: true })
      : spawn("pi", args, { windowsHide: true });
    let out = "", err = "";
    const timer = setTimeout(() => { try { child.kill(); } catch {} resolve({ ok: false, error: "超时（3 分钟）", output: out.slice(-1200) }); }, LIMITS.PKG_TIMEOUT);
    child.stdout.on("data", (d) => (out += d));
    child.stderr.on("data", (d) => (err += d));
    child.on("error", (e) => { clearTimeout(timer); resolve({ ok: false, error: String(e?.message || e) }); });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ ok: code === 0, code, output: (out + "\n" + err).trim().slice(-1600) });
    });
  });
  const pkgTypes = (p) => {
    const kws = (p.keywords || []).map((k) => String(k).toLowerCase());
    const hay = [p.name || "", p.description || "", kws.join(" ")].join(" ").toLowerCase();
    const kwHas = (t) => kws.includes("pi-" + t) || kws.includes(t) || kws.includes(t + "s");
    const txtHas = (t) => hay.includes(t);
    const types = [];
    if (kwHas("skill") || (txtHas("skill") && !kws.includes("pi-extension"))) types.push("skill");
    if (kwHas("theme") || txtHas("theme")) types.push("theme");
    if (kwHas("prompt") || txtHas("prompt")) types.push("prompt");
    if (kwHas("extension") || /extension|adapter|toolbar|footer|overlay|dashboard|integrat|workflow/.test(hay)) types.push("extension");
    if (!types.length) types.push(kws.length ? "extension" : "package");
    return types;
  };
  handle("halo:pkg-search", async ({ query = "", from = 0, size = 20, type = "" } = {}) => {
    // 分类用裸关键词下推到 npm 服务端（extension/skill/theme/prompt），与官网分类口径一致
    // （glimpseui 等官网 prompt 包带裸 "prompt" 关键词；pi-prompt 显式关键词只有少数包用）
    const t = ["extension", "skill", "theme", "prompt"].includes(String(type)) ? String(type) : "";
    const text = encodeURIComponent("keywords:pi-package" + (t ? "," + t : "") + (String(query).trim() ? " " + String(query).trim() : ""));
    const res = await fetch(`https://registry.npmjs.org/-/v1/search?text=${text}&size=${size}&from=${from}`);
    if (!res.ok) throw new Error("npm 搜索失败 " + res.status);
    const j = await res.json();
    const items = (j.objects || []).map((o) => {
      const p = o.package || {};
      return {
        name: p.name || "",
        desc: p.description || "",
        version: p.version || "",
        date: p.date || "",
        author: p.publisher?.username || (typeof p.author === "string" ? p.author : p.author?.name) || "",
        repo: p.links?.repository || p.links?.homepage || "",
        types: pkgTypes(p),
      };
    });
    return { total: j.total || items.length, items };
  });
  /* 已安装列表 + 版本检测（本地 version vs registry latest → 待更新标记） */
  const collectPkgs = async () => {
    const st = readPiSettings();
    const list = (st.packages || []).map((p) => {
      if (typeof p === "string") {
        const kind = p.startsWith("npm:") ? "npm" : p.startsWith("git:") || /^https?:\/\//.test(p) ? "git" : "本地";
        return { raw: p, source: p, kind, disabled: false };
      }
      const src = p.source || "";
      const kind = src.startsWith("npm:") ? "npm" : src.startsWith("git:") || /^https?:\/\//.test(src) ? "git" : "本地";
      const disabled = ["extensions", "skills", "prompts", "themes"].every((k) => Array.isArray(p[k]) && p[k].length === 0);
      return { raw: src, source: src, kind, disabled };
    });
    await Promise.all(list.filter((p) => p.kind === "npm").map(async (p) => {
      const name = p.source.replace(/^npm:/, "").replace(/@[\w.+-]+$/, (m, off) => (off === 0 || p.source[off - 1] === "/" ? m : ""));
      try {
        const pj = JSON.parse(fs.readFileSync(path.join(piHome(), "npm", "node_modules", name, "package.json"), "utf8"));
        p.version = pj.version || "";
      } catch {}
      try {
        const res = await fetch("https://registry.npmjs.org/" + name.split("/").map(encodeURIComponent).join("/") + "/latest");
        if (res.ok) {
          const j = await res.json();
          p.latest = j.version || "";
          p.update = !!p.version && !!p.latest && p.version !== p.latest;
        }
      } catch {}
    }));
    return list;
  };
  handle("halo:pkg-installed", async () => collectPkgs());
  /* 包源白名单：只允许 npm:/git:/https:/本地路径，且不含空格与任何 shell 元字符
   * （npm 包名/版本、git URL 均满足此约束）—— 即使参数拼入 cmd 命令行也不可能注入 */
  const PKG_SOURCE_RE = /^(npm:[A-Za-z0-9@._~/-]+(@[A-Za-z0-9._-]+)?|git:[^\s"'&|;<>()$`\\]+|https?:\/\/[^\s"'&|;<>()$`]+|\.\.?\/[^\s"'&|;<>()$`]+|[a-zA-Z]:\\[^\s"'&|;<>()$`]*)$/;
  const ensureSource = (source) => {
    if (!PKG_SOURCE_RE.test(String(source || ""))) throw new Error("不支持的包源：" + source);
    return source;
  };
  handle("halo:pkg-install", async ({ source }) => {
    ensureSource(source);
    const r = await spawnPi(["install", source]);
    if (!r.ok) throw new Error(r.error || r.output || `退出码 ${r.code}`);
    return { output: r.output };
  });
  handle("halo:pkg-remove", async ({ source }) => {
    ensureSource(source);
    const r = await spawnPi(["remove", source]);
    if (!r.ok) throw new Error(r.error || r.output || `退出码 ${r.code}`);
    return { output: r.output };
  });
  handle("halo:pkg-update", async ({ source }) => {
    ensureSource(source);
    const r = await spawnPi(["update", source]);
    if (!r.ok) throw new Error(r.error || r.output || `退出码 ${r.code}`);
    return { output: r.output };
  });
  /* 一键更新：逐个更新所有待更新包（版本落后的 npm 包，逐个过白名单再执行） */
  handle("halo:pkg-update-all", async () => {
    const list = await collectPkgs();
    const targets = list.filter((p) => p.update);
    const results = [];
    for (const t of targets) {
      try { ensureSource(t.raw); } catch { results.push({ source: t.raw, ok: false, error: "包源不合法，已跳过" }); continue; }
      const r = await spawnPi(["update", t.raw]);
      results.push({ source: t.raw, ok: r.ok, error: r.ok ? undefined : (r.error || r.output || `退出码 ${r.code}`) });
    }
    return { total: targets.length, updated: results.filter((r) => r.ok).map((r) => r.source), failed: results.filter((r) => !r.ok) };
  });
  /* 启用 / 停用：停用 = settings 里该包改为全空 filter 对象（官方过滤机制），启用 = 恢复字符串 */
  handle("halo:pkg-toggle", async ({ raw, on }) => {
    const st = readPiSettings();
    const list = Array.isArray(st.packages) ? st.packages : [];
    const idx = list.findIndex((p) => (typeof p === "string" ? p : p.source) === raw);
    if (idx < 0) throw new Error("未找到该包：" + raw);
    if (on) {
      list[idx] = typeof list[idx] === "string" ? list[idx] : list[idx].source;
    } else {
      const src = typeof list[idx] === "string" ? list[idx] : list[idx].source;
      list[idx] = { source: src, extensions: [], skills: [], prompts: [], themes: [] };
    }
    st.packages = list;
    writePiSettings(st);
    return true;
  });
  handle("halo:projects-list", async () => bridge.projectsList());
  handle("halo:project-switch", async ({ cwd }) => bridge.switchProject(cwd));
  handle("halo:project-add", async ({ dir }) => bridge.addProject(dir));
  handle("halo:project-remove", async ({ cwd }) => bridge.removeProject(cwd));
  handle("halo:agent-list", async () => scanAgents(bridge.cwd));
  handle("halo:agent-default-get", async () => store.data.defaultAgent || "");
  handle("halo:agent-default-set", async ({ name }) => {
    store.set("defaultAgent", name || "");
    return true;
  });

  handle("halo:pkg-reload", async () => {
    await bridge.start(bridge.cwd);
    return true;
  });

  handle("halo:pick-images", async () => {
    const res = await dialog.showOpenDialog(mainWin, {
      title: "附加图片",
      filters: [{ name: "Images", extensions: ["png", "jpg", "jpeg", "webp", "gif"] }],
      properties: ["openFile", "multiSelections"],
    });
    if (res.canceled) return { files: [], skipped: [] };
    const files = [], skipped = [];
    for (const p of res.filePaths) {
      try {
        if (fs.statSync(p).size > LIMITS.IMAGE_PICK) { skipped.push(path.basename(p)); continue; }
        const b = fs.readFileSync(p).toString("base64");
        const ext = path.extname(p).slice(1).toLowerCase();
        const mediaType = ext === "jpg" ? "image/jpeg" : `image/${ext}`;
        files.push({ name: path.basename(p), mediaType, data: b });
      } catch { skipped.push(path.basename(p)); }
    }
    return { files, skipped };
  });

  // window controls
  ipcMain.on("win:minimize", () => mainWin?.minimize());
  ipcMain.on("win:maximize", () => (mainWin?.isMaximized() ? mainWin.unmaximize() : mainWin?.maximize()));
  ipcMain.on("win:close", () => mainWin?.close());

  /* ---------------- app lifecycle ---------------- */

  app.on("second-instance", () => {
    if (mainWin) {
      if (mainWin.isMinimized()) mainWin.restore();
      mainWin.focus();
    }
  });

  app.whenReady().then(() => {
    // preview protocol: serve workspace files to the Preview iframe safely
    const MIME = {
      ".html": "text/html", ".htm": "text/html", ".css": "text/css",
      ".js": "text/javascript", ".mjs": "text/javascript", ".json": "application/json",
      ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
      ".gif": "image/gif", ".webp": "image/webp", ".svg": "image/svg+xml",
      ".md": "text/markdown", ".txt": "text/plain", ".mp4": "video/mp4",
      ".webm": "video/webm", ".pdf": "application/pdf",
    };
    protocol.handle("halo-preview", async (request) => {
      try {
        const u = new URL(request.url);
        let p = decodeURIComponent(u.pathname);
        if (process.platform === "win32") p = p.replace(/^\//, "");
        p = path.normalize(p);
        if (!isInsideProject(p)) return new Response("forbidden", { status: 403 });
        const st = await fs.promises.stat(p).catch(() => null);
        if (!st) return new Response("not found", { status: 404 });
        if (st.size > LIMITS.PREVIEW) return new Response("too large", { status: 413 });
        const ext = path.extname(p).toLowerCase();
        const buf = await fs.promises.readFile(p);
        const mime = MIME[ext] || "application/octet-stream";
        // 文本类补 charset，避免无 meta 声明的文件乱码
        const ct = /^text\//.test(mime) || /(javascript|json|svg)/.test(mime) ? `${mime}; charset=utf-8` : mime;
        return new Response(buf, { headers: { "content-type": ct, "cache-control": "no-store" } });
      } catch {
        return new Response("not found", { status: 404 });
      }
    });

    createSplash();
  });

  app.on("window-all-closed", () => {
    app.quit();
  });
}
