import { isTrustedUIURL } from "./trusted-ui-url.mjs";
import electronUpdater from 'electron-updater';
import { createAppUpdates } from './app-updates.mjs';
import { createStartupLifecycle } from './startup-lifecycle.mjs';
import { inspectPreview } from "./preview-inspection.mjs";
import { previewDocument } from "./document-preview.mjs";
/**
 * Pi Halo — Electron main process
 * splash (launch animation) -> main window (three-panel celestial console)
 */

import { app, BrowserWindow, session, ipcMain, dialog, shell, protocol, safeStorage, clipboard, nativeImage, ClipboardItem } from "electron";
import path from "node:path";
import fs from "node:fs";
import { X509Certificate } from "node:crypto";
import { spawnPi as runPiCommand } from "./pi-command.mjs";
import { ServerManager, parseListeningPorts } from "./servers.mjs";
import { TerminalPool } from "./terminal-pool.mjs";
import { isInsideWorkspace } from "./workspace-path.mjs";
import { readPreviewFile } from "./read-preview-file.mjs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { PiBridge, HaloStore, scanAgents } from "./pi-bridge.mjs";
import { configureEnvironmentProxy } from "./env-proxy.mjs";
import { EnvironmentManager } from "./environment-manager.mjs";
import { GitHubAuth } from './github-auth.mjs';
import { CloudflareService } from './cloudflare.mjs';
import os from "node:os";
import { VideoSettings } from "./video-settings.mjs";
import { VideoPricing } from "./video-pricing.mjs";
import { VideoGeneration } from "./video-generation.mjs";
import { videoResponse } from "./video-preview.mjs";

// Applies to both npm start and the installed EXE, before Pi/OAuth can fetch.
configureEnvironmentProxy();

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.join(HERE, "..", "..");
const PRELOAD = path.join(DIST, "src", "preload", "preload.cjs");
const ICON = path.join(DIST, "assets", "icon-rounded.png");

/* 统一限额/常量（调参只改这里） */
const LIMITS = {
  TREE_CAP: 1200,        // 文件树最多条目
  TREE_DEPTH: 8,         // 文件树最大深度
  FILE_READ: 512 * 1024, // 单文件读取上限
  PREVIEW: 8 * 1024 * 1024,  // 预览协议单文件上限
  IMAGE_PICK: 25 * 1024 * 1024, // 附加图片单张上限
  EARLY_EVENTS: 500,     // 主窗口就绪前的事件缓冲
  TREE_WATCH_DEBOUNCE: 600, // 文件树 watcher 防抖
  PKG_TIMEOUT: 180000,   // pi CLI 子进程超时
};

/* 路径归一化：Windows 反斜杠 → 正斜杠、去尾斜杠、小写（仅用于比较） */
const normP = (p) => String(p || "").replace(/\\/g, "/").replace(/\/$/, "").toLowerCase();

/* 凭据保管库加密（Windows DPAPI / macOS Keychain，不可用时回退明文） */
const seal = (s) => {
  try {
    if (safeStorage?.isEncryptionAvailable?.()) return safeStorage.encryptString(s).toString("base64");
  } catch {}
  return null;
};
const unseal = (s) => {
  try {
    if (safeStorage?.isEncryptionAvailable?.()) return safeStorage.decryptString(Buffer.from(s, "base64"));
  } catch {}
  return null;
};

/* 预览注入脚本（独立文件，便于 lint / 语法检查） */
const readInject = (name) => fs.readFileSync(path.join(HERE, "inject", name), "utf8");
const TOUCH_ON = readInject("touch-on.js");
const TOUCH_OFF = readInject("touch-off.js");
const SCROLL_STYLE = readInject("scroll-style.js");

/* pi SDK 会随会话运行时/扩展环境注册一组关闭钩子（SIGINT/SIGTERM/beforeExit），
 * 重建几次后数量超过 Node 默认上限 10，触发“内存泄漏”误报。
 * 这些钩子是 SDK 的正常清理逻辑，并非泄漏 —— 这里取消上限以消除噪音。 */
process.setMaxListeners?.(0);

// privileged scheme so the Preview pane can load workspace files in an iframe
protocol.registerSchemesAsPrivileged([
  { scheme: "halo-preview", privileges: { standard: true, secure: true, supportFetchAPI: true, stream: true } },
]);

app.setName("Pi Halo");

let splashWin = null;
let mainWin = null;
let quitting = false;

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  // 已有实例在跑：干净退出（exit 0），避免 npm start 报 “exited with code 127”；
  // first 实例会收到 second-instance 事件并聚焦已有窗口
  app.exit(0);
} else {
  bootstrap();
}

/* 生成默认智能体注入扩展：每次 agent 启动前实时读 halo-settings.json，把选中智能体的提示追加到系统提示 */
/* 生成默认智能体注入扩展：每次 agent 启动前实时读 halo-settings.json，把选中智能体的提示追加到系统提示。
 * 实际 handler 在 pi-bridge 的 extensionsOverride 内联实现；这里只写一个最小存根文件
 * （loader 需要 path 指向真实存在的文件），避免双份维护扫描逻辑。 */
/* 生成默认智能体注入扩展：每次 agent 启动前实时读 halo-settings.json，把选中智能体的提示追加到系统提示。
 * 实际 handler 在 pi-bridge 的 extensionsOverride 内联实现；这里只写一个最小存根文件
 * （loader 需要 path 指向真实存在的文件），避免双份维护扫描逻辑。 */
function writeAgentExt(storeFile) {
  const file = path.join(path.dirname(storeFile), "halo-default-agent-ext.mjs");
  const code = "/* Generated by Pi Halo — default agent injection. Do not edit. */\nexport default function () {};\n";
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, code);
  } catch (e) {
    console.error("[halo] write agent ext failed:", e);
  }
  return file;
}

function bootstrap() {
  const store = new HaloStore(path.join(app.getPath("userData"), "halo-settings.json"));
  const bridge = new PiBridge(store, { seal, unseal });
  const videoSettings = new VideoSettings(path.join(os.homedir(), '.pi', 'agent', 'halo-video.json'), { seal, unseal });
  const videoPricing = new VideoPricing();
  const video = new VideoGeneration(videoSettings, path.join(os.homedir(), '.pi', 'agent', 'halo-video-jobs.json'), { pricing: videoPricing });
  video.confirmGeneration = async (request, signal) => {
    if (signal?.aborted || !mainWin || mainWin.isDestroyed()) return false;
    const estimate = request.estimate;
    const cost = estimate?.available && Number.isFinite(estimate.total)
      ? `${Number(estimate.total.toFixed(4))} ${estimate.currency === 'Credits' ? '积分' : estimate.currency}` : '暂不可用，以平台实际计费为准';
    const { response } = await dialog.showMessageBox(mainWin, {
      type: 'question', title: '确认视频生成', message: '是否调用视频模型生成？',
      detail: `${request.providerName} · ${request.model}\n${request.resolution} · ${request.duration} 秒 · ${request.ratio}\n预估消耗：${cost}\n项目：${request.cwd}\n\n${request.prompt.slice(0, 600)}`,
      buttons: ['使用其他方式', '确认生成视频'], defaultId: 0, cancelId: 0, noLink: true,
    });
    return response === 1 && !signal?.aborted;
  };
  bridge.video = video;
  const servers = new ServerManager(store, seal, unseal);
  bridge.servers = servers;
  app.on("certificate-error", (event, contents, url, _error, certificate, callback) => {
    const normalize = value => String(value || "").replace(/:/g, "").toLowerCase();
    const trusted = contents.getType() === "webview" && [...servers.previews.values()].some(preview => {
      try { return preview.fingerprint && new URL(preview.url).origin === new URL(url).origin && normalize(preview.fingerprint) === normalize(new X509Certificate(certificate.data).fingerprint256); } catch { return false; }
    });
    if (trusted) { event.preventDefault(); callback(true); } else callback(false);
  });
  app.on("before-quit", () => servers.dispose());

  // 生成默认智能体注入扩展（每次启动重写，路径/配置指向最新）
  writeAgentExt(store.file);

  /* A created window is not yet a listening renderer. Retain startup errors as well as events. */
  const pendingEvents = [];
  let rendererReady = false;
  let pendingState = null;
  const emit = (channel, payload) => {
    if (rendererReady && mainWin && !mainWin.isDestroyed()) { mainWin.webContents.send(channel, payload); return; }
    if (channel === 'halo:state') pendingState = payload;
    if (channel === "pi:event" || channel === 'halo:error') {
      pendingEvents.push({ channel, payload });
      if (pendingEvents.length > LIMITS.EARLY_EVENTS) pendingEvents.shift();
    }
  };
  const flushPendingEvents = () => {
    if (!rendererReady || !mainWin || mainWin.isDestroyed()) return;
    if (pendingState) { mainWin.webContents.send('halo:state', pendingState); pendingState = null; }
    while (pendingEvents.length) {
      const { channel, payload } = pendingEvents.shift();
      mainWin?.webContents.send(channel, payload);
    }
  };
  bridge.onEvent(emit);
  const environment = new EnvironmentManager({ onChange: state => emit('halo:environment-progress', state) });
  const githubAuth = new GitHubAuth();
  const cloudflareDir = path.join(app.getPath('userData'), 'cloudflare');
  fs.mkdirSync(cloudflareDir, { recursive: true });
  const cloudflare = new CloudflareService({ cwd: cloudflareDir });
  bridge.cloudflare = cloudflare;

  /* ---------------- splash ---------------- */
  let startupWatchdog;
  let startupFailureShowing = false;
  let coreStartPromise;
  const startup = createStartupLifecycle({
    onChange: state => {
      if (process.env.HALO_STARTUP_TRACE === '1') console.log('[halo:startup]', JSON.stringify({
        timings: state.timings, steps: state.steps.map(({ id, status }) => ({ id, status })), elapsedMs: state.elapsedMs,
      }));
      if (splashWin && !splashWin.isDestroyed()) splashWin.webContents.send('halo:startup-progress', state);
      emit('halo:startup-progress', state);
    },
    onInterfaceReady: () => {
      clearTimeout(startupWatchdog);
      // Warm the core while the small launch window stays visible.
      setImmediate(() => { if (!quitting) void startCore().catch(() => {}); });
    },
    reveal: () => {
      if (quitting || !mainWin || mainWin.isDestroyed()) return;
      clearTimeout(startupWatchdog);
      mainWin.show();
      mainWin.webContents.setBackgroundThrottling(true);
      mainWin.focus();
      if (splashWin && !splashWin.isDestroyed()) splashWin.close();
      splashWin = null;
      emit('halo:window-shown', {});
      flushPendingEvents();
    },
  });
  function startCore() {
    if (coreStartPromise) return coreStartPromise;
    if (bridge.publicState().ready) return Promise.resolve(bridge.publicState());
    startup.begin('core', '正在加载本地模型配置、扩展和上次会话');
    const startCwd = store.data.cwd || path.join(app.getPath('home'), 'Desktop');
    coreStartPromise = bridge.start(startCwd).then(state => {
      startup.complete('core');
      startup.begin('workspace', '正在恢复聊天记录、项目和文件列表');
      return state;
    }).catch(error => {
      console.error('[halo] bridge start failed:', error);
      startup.fail('core', error);
      emit('halo:error', { message: String(error?.message || error) });
      throw error;
    }).finally(() => { coreStartPromise = null; });
    return coreStartPromise;
  }
  async function showStartupFailure(error) {
    if (startupFailureShowing || quitting) return;
    startupFailureShowing = true;
    clearTimeout(startupWatchdog);
    startup.fail('interface', error);
    const owner = splashWin && !splashWin.isDestroyed() ? splashWin : mainWin;
    const options = { type: 'error', title: 'Pi Halo 启动未完成', message: '主界面未能正常加载',
      detail: `${String(error?.message || error)}\n\n可以重试启动。项目、聊天记录和账户配置会保留。`,
      buttons: ['重试启动', '退出'], defaultId: 0, cancelId: 1, noLink: true };
    const { response } = owner && !owner.isDestroyed() ? await dialog.showMessageBox(owner, options) : await dialog.showMessageBox(options);
    if (quitting) return;
    if (response === 0) app.relaunch();
    app.quit();
  }
  app.once('before-quit', () => {
    if (!quitting) {
      quitting = true;
      disarmTreeWatcher();
      bridge.dispose();
    }
    startup.dispose();
    clearTimeout(startupWatchdog);
  });

  function createSplash() {
    splashWin = new BrowserWindow({
      width: 520,
      height: 360,
      icon: ICON,
      frame: false,
      transparent: true,
      resizable: false,
      movable: false,
      skipTaskbar: true,
      alwaysOnTop: true,
      show: false,
      backgroundColor: "#00000000",
      webPreferences: {
        preload: PRELOAD,
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true,
      },
    });
    const window = splashWin;
    window.on('close', () => {
      if (!quitting && startup.snapshot().timings.windowShown === undefined) app.quit();
    });
    window.once("ready-to-show", () => {
      if (quitting || window.isDestroyed() || mainWin?.isVisible()) return;
      window.center();
      window.show();
      window.focus();
    });
    window.loadFile(path.join(DIST, "src", "renderer", "splash.html")).catch(error => {
      console.error('[halo] splash load failed:', error);
      // The decorative launch card must not prevent the main window from opening.
      if (!window.isDestroyed()) window.destroy();
      if (splashWin === window) splashWin = null;
    });
  }

  /* ---------------- main window ---------------- */

  function createMainWindow() {
    mainWin = new BrowserWindow({
      width: 1440,
      height: 900,
      minWidth: 1120,
      minHeight: 720,
      icon: ICON,
      frame: false,
      show: false,
      backgroundColor: "#0b0b0c",
      titleBarStyle: "hidden",
      webPreferences: {
        preload: PRELOAD,
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true,
        spellcheck: false,
        // Allow the hidden workspace to finish painting before the handoff.
        backgroundThrottling: false,
        webviewTag: true,
      },
    });

    mainWin.webContents.on("will-attach-webview", (event, preferences, params) => {
      // Isolate public websites from the app and from SSH preview sessions.
      let website = false;
      try { const url = new URL(params.src); website = params.partition === 'website-preview' && ['http:', 'https:'].includes(url.protocol) && !url.username && !url.password; } catch {}
      if (!website && ![...servers.previews.values()].some(p => p.url === params.src)) { event.preventDefault(); return; }
      delete preferences.preload;
      delete preferences.preloadURL;
      if (website) preferences.preload = path.join(DIST, 'src', 'preload', 'website-preview.cjs');
      preferences.nodeIntegrationInSubFrames = false; preferences.nodeIntegrationInWorker = false;
      preferences.webviewTag = false;
      preferences.nodeIntegration = false; preferences.contextIsolation = true;
      preferences.sandbox = true; preferences.webSecurity = true;
    });
    mainWin.webContents.on("did-attach-webview", (_event, guest) => {
      previewGuests.add(guest);
      // Manual mode reports a zoom factor without applying it to the page.
      if (guest.session === session.fromPartition('website-preview')) guest.setZoomMode('isolated');
      guest.on('zoom-changed', (_event, direction) => {
        if (guest.session === session.fromPartition('website-preview') && mainWin && !mainWin.isDestroyed()) {
          mainWin.webContents.send('halo:website-zoom', {guestId:guest.id, direction});
        }
      });
      guest.once("destroyed", () => previewGuests.delete(guest));
      guest.setWindowOpenHandler(({url}) => {
        if (/^https?:\/\//.test(url)) void guest.loadURL(url).catch(() => {});
        return { action: "deny" };
      });
      guest.session.setPermissionRequestHandler((_wc, _permission, callback) => callback(false));
      guest.on("will-navigate", (event, url) => { if (!/^https?:\/\//.test(url)) event.preventDefault(); });
      guest.on("dom-ready", () => { guest.executeJavaScript(SCROLL_STYLE).catch(() => {}); guest.executeJavaScript(previewTouch ? TOUCH_ON : TOUCH_OFF).catch(() => {}); });
    });
    mainWin.webContents.on("render-process-gone", (_event, details) => {
      terminals.dispose();
      if (!quitting) void showStartupFailure(`界面进程意外退出：${details.reason}`);
    });
    mainWin.once("ready-to-show", () => startup.painted());
    mainWin.loadFile(path.join(DIST, "src", "renderer", "index.html")).catch(error => {
      if (!quitting) void showStartupFailure(error);
    });
    mainWin.on("maximize", () => emit("halo:winstate", { maximized: true }));
    mainWin.on("unmaximize", () => emit("halo:winstate", { maximized: false }));
    mainWin.on("closed", () => {
      mainWin = null;
      if (splashWin && !splashWin.isDestroyed()) splashWin.close();
      splashWin = null;
    });
    mainWin.on("close", () => {
      if (!quitting) {
        quitting = true;
        startup.dispose();
        clearTimeout(startupWatchdog);
        disarmTreeWatcher();
        bridge.dispose();
      }
    });
    // open external links in browser（只放行 https，其余一律拒绝）
    mainWin.webContents.setWindowOpenHandler(({ url }) => {
      if (/^https?:\/\//.test(url)) shell.openExternal(url);
      return { action: "deny" };
    });
  }

  /* ---------------- IPC ---------------- */

  // 预览触摸模拟：平板/手机模式隐藏滚动条 + 按住拖动滚动 + 松手惯性 + 拖动后抑制误点击
  let previewTouch = false;
  const previewGuests = new Set();
  bridge.inspectPreview = options => inspectPreview({...options, guests:previewGuests, previews:servers.previews.values()});
  /* 预览触摸模拟 / 滚动条美化脚本：独立文件注入（src/main/inject/），
   * 平板/手机模式隐藏滚动条 + 按住拖动滚动 + 松手惯性 + 拖动后抑制误点击 */
  const applyPreviewTouch = (attempt = 0) => {
    const frames = (() => {
      try { return mainWin?.webContents.mainFrame.frames || []; } catch { return []; }
    })();
    const hits = [...frames.filter((f) => String(f.url).startsWith("halo-preview://")), ...[...previewGuests].filter(g => !g.isDestroyed())];
    if (!hits.length) {
      // iframe 可能尚未挂载，重试几次；关闭开关时无需重试
      if (previewTouch && attempt < 6) setTimeout(() => applyPreviewTouch(attempt + 1), 250);
      return;
    }
    for (const f of hits) {
      Promise.resolve(f.executeJavaScript(SCROLL_STYLE)).catch(() => {});
      Promise.resolve(f.executeJavaScript(previewTouch ? TOUCH_ON : TOUCH_OFF)).catch(() => {});
    }
  };

  const trustedSender = (event, splash = false) => {
    const window = splash ? splashWin : mainWin;
    if (!window || window.isDestroyed()) return false;
    const contents = window.webContents;
    const expected = pathToFileURL(path.join(DIST, 'src', 'renderer', splash ? 'splash.html' : 'index.html')).href;
    return event.sender === contents && event.senderFrame === contents.mainFrame && isTrustedUIURL(event.senderFrame?.url, expected);
  };
  const handle = (channel, fn) => {
    ipcMain.handle(channel, async (e, ...args) => {
      try {
        const trusted = channel === 'halo:startup-state'
          ? trustedSender(e) || trustedSender(e, true)
          : trustedSender(e, channel === 'halo:splash-done');
        if (!trusted) throw Error('不可信的界面请求');
        return { ok: true, data: await fn(...args) };
      } catch (err) {
        return { ok: false, error: String(err?.message || err) };
      }
    });
  };

  handle('halo:splash-done', () => startup.snapshot());
  handle('halo:startup-state', () => startup.snapshot());
  handle('halo:renderer-ready', () => {
    if (startupFailureShowing || quitting) return startup.snapshot();
    rendererReady = true;
    flushPendingEvents();
    startup.wired();
    return startup.snapshot();
  });
  handle('halo:renderer-failed', error => { void showStartupFailure(String(error || '界面初始化失败')); });
  handle('halo:startup-retry', async () => {
    const state = await startCore();
    startup.begin('workspace', '正在重新恢复聊天记录、项目和文件列表');
    return state;
  });
  handle('halo:workspace-ready', error => {
    if (error) startup.fail('workspace', String(error));
    else startup.complete('workspace');
    return startup.snapshot();
  });

  handle("halo:server-latencies", (force) => servers.latencies(force === true));
  handle("halo:server-latency", (id) => servers.latency(id, true));
  handle("halo:server-list", async () => ({ items: servers.list(), conversations: await bridge.serverConversations(), selected: bridge.serverTargets?.get(bridge.session?.sessionId) || null }));
  handle("halo:server-new-session", (id) => switchSession(async () => {
    if (!servers.list().some(s => s.id === id)) throw Error("服务器不存在");
    return bridge.newSession(id);
  }));
  handle("halo:server-preview", (id, item) => servers.preview(id, item));
  handle("halo:server-ports", async (id) => {
    const result = await servers.exec(id, "if command -v ss >/dev/null 2>&1; then ss -H -lntup; elif command -v netstat >/dev/null 2>&1; then netstat -lntup; else echo '服务器未安装 ss 或 netstat' >&2; exit 1; fi");
    if (result.code !== 0) throw Error(result.output || "读取端口失败");
    return { items: parseListeningPorts(result.output), updated: Date.now() };
  });
  const updates = createAppUpdates({updater:electronUpdater.autoUpdater, app, getWindow:() => mainWin,
    emit:state => emit('halo:app-update', state)});
  handle('halo:check-app-update', () => updates.check(true));
  handle('halo:app-update-state', () => updates.getState());
  handle('halo:download-app-update', () => updates.download());
  if (app.isPackaged && process.env.PI_OFFLINE !== '1') {
    const firstCheck = setTimeout(() => void updates.check(), 30000);
    const nextChecks = setInterval(() => void updates.check(), 6 * 60 * 60 * 1000);
    firstCheck.unref(); nextChecks.unref();
    app.once('before-quit', () => { clearTimeout(firstCheck); clearInterval(nextChecks); });
  }
  handle("halo:server-save", (input) => { if (input.id && bridge.isServerBusy(input.id)) throw Error("服务器任务正在运行，请结束后再编辑"); return servers.save(input); });
  handle("halo:server-select", (id) => switchSession(async () => {
    const session = bridge.session;
    if (!session) throw Error("请等待会话就绪");
    if (session.isStreaming) throw Error("请等待当前任务结束后切换服务器");
    if (id) await servers.connect(id);
    if (session !== bridge.session || session.isStreaming) throw Error("会话状态已变化，请重新选择服务器");
    const previous = id && store.data.serverLastSessions?.[id];
    if (previous && fs.existsSync(previous) && previous !== session.sessionFile) await bridge.openSession(previous);
    bridge.serverTargets.set(bridge.session.sessionId, id || null);
    store.set("serverTargets", Object.fromEntries(bridge.serverTargets));
    bridge._noteSession();
    bridge.pushState();
    return bridge.publicState();
  }));
  handle("halo:server-reorder", (ids) => servers.reorder(ids));
  handle("halo:server-remove", (id) => switchSession(() => bridge.removeServer(id)));
  handle("halo:environment-status", () => environment.status());
  handle('halo:github-status', () => githubAuth.status());
  handle('halo:cloudflare-status', () => cloudflare.status());
  handle('halo:cloudflare-login', () => cloudflare.auth('login'));
  handle('halo:cloudflare-logout', () => cloudflare.auth('logout'));
  handle('halo:github-login', () => githubAuth.login());
  handle('halo:github-logout', account => githubAuth.logout(account));
  handle("halo:environment-install", () => {
    if (environmentRepairBusy) throw Error('请等待 AI 修复结束');
    return environment.start();
  });
  let environmentRepairBridge = null;
  let environmentRepairBusy = false;
  let environmentRepairCancelled = false;
  handle('halo:environment-repair-stop', () => {
    environmentRepairCancelled = true;
    return environmentRepairBridge?.abort();
  });
  handle("halo:environment-repair", async () => {
    if (environmentRepairBusy) throw Error('AI 修复正在进行中');
    environmentRepairBusy = true;
    environmentRepairCancelled = false;
    try {
    const prompt = await environment.repairPrompt();
    if (environmentRepairCancelled) throw Error('已停止 AI 修复');
    if (!prompt) return { ...environment.snapshot(), repairSkipped: true };
    const key = store.data.defaultModel || store.data.modelKey;
    if (!key) throw Error('请先配置默认大模型');
    const dir = path.join(app.getPath('userData'), 'environment-repair');
    fs.mkdirSync(dir, { recursive: true });
    const repairStore = new HaloStore(path.join(dir, 'settings.json'));
    repairStore.set('projects', []);
    repairStore.set('defaultModel', key);
    const repair = new PiBridge(repairStore, { seal, unseal }, { sessionDir: path.join(dir, 'sessions') });
    environmentRepairBridge = repair;
    repair.onEvent((channel, payload) => {
      if (channel === 'pi:event') emit('halo:environment-repair-progress', payload.event);
    });
    try {
      await repair.start(dir);
      const [provider, ...model] = key.split('/');
      await repair.setModel(provider, model.join('/'));
      repair.setThinkingLevel('minimal');
      if (environmentRepairCancelled) throw Error('已停止 AI 修复');
      await repair.prompt(prompt);
      return await environment.status();
    } finally {
      await repair.dispose();
      environmentRepairBridge = null;
    }
    } finally { environmentRepairBusy = false; }
  });
  handle("halo:video-settings", () => videoSettings.publicState());
  handle("halo:video-balance", input => video.balance(input));
  handle("halo:video-history", () => video.consumptionHistory());
  handle("halo:video-save", input => videoSettings.save(input));
  handle("halo:video-test", input => video.test(input));
  handle("halo:video-estimate", input => videoPricing.estimate(input));
  handle("halo:video-model-prices", input => videoPricing.models(input));
  handle("halo:get-state", () => bridge.publicState());
  handle("halo:init", (cwd) => bridge.start(cwd));
  handle("halo:prompt", (text, opts) => bridge.prompt(text, opts));
  handle("halo:steer", (text) => bridge.steer(text));
  handle("halo:followUp", (text) => bridge.followUp(text));
  handle("halo:abort", () => bridge.abort());
  handle("halo:compact", (instructions) => bridge.compact(instructions));
  handle("halo:list-models", () => bridge.listModels());
  handle("halo:default-model-get", async () => store.data.defaultModel || "");
  handle("halo:default-model-set", async ({ key }) => {
    store.set("defaultModel", key || "");
    return true;
  });
  handle("halo:set-model", (provider, id) => bridge.setModel(provider, id));
  handle("halo:set-thinking", (level) => bridge.setThinkingLevel(level));
  handle("halo:list-sessions", () => bridge.listSessions());
  handle("halo:usage-summary", (args) => bridge.usageSummary(args?.days || 30));
  handle("halo:model-quota", (provider, force) => bridge.modelQuota(provider, force));

  // auth / login（与 pi CLI 共享 ~/.pi/agent/auth.json）
  handle("halo:auth-providers", () => bridge.authProviders());
  handle("halo:auth-login", (providerId, type) => bridge.authLogin(providerId, type));
  handle("halo:auth-respond", (value) => bridge.authPromptRespond(value));
  handle("halo:auth-cancel", () => bridge.authCancel());
  handle("halo:auth-logout", (providerId) => bridge.authLogout(providerId));
  // 多账户：保存当前身份 / 一键切换 / 删除 / 重命名
  handle("halo:auth-account-capture", (providerId, label) => bridge.authAccountCapture(providerId, label));
  handle("halo:auth-account-switch", (providerId, accountId) => bridge.authAccountSwitch(providerId, accountId));
  handle("halo:auth-account-remove", (providerId, accountId) => bridge.authAccountRemove(providerId, accountId));
  handle("halo:auth-account-rename", (providerId, accountId, label) => bridge.authAccountRename(providerId, accountId, label));
  handle("halo:auth-account-quotas", (providerId) => bridge.authAccountsQuota(providerId));
  handle("halo:ext-toggle", (extPath, enabled) => bridge.setExtensionEnabled(extPath, enabled));
  let sessionSwitchQueue = Promise.resolve();
  const switchSession = (action) => {
    const result = sessionSwitchQueue.then(async () => {
      // Startup may still be warming the first runtime when the UI restores a project.
      if (bridge.startingPromise) await bridge.startingPromise;
      return action();
    });
    sessionSwitchQueue = result.catch(() => {});
    return result;
  };
  handle("halo:open-session", (file) => switchSession(() => bridge.openSession(file)));
  handle("halo:new-session", () => switchSession(() => bridge.newSession()));
  handle("halo:delete-session", (file) => switchSession(() => bridge.deleteSession(file)));
  handle("halo:preview-touch", async ({ on }) => {
    previewTouch = !!on;
    applyPreviewTouch();
    return { on: previewTouch };
  });
  handle("halo:snapshot-messages", () => bridge.snapshotMessages());
  handle("halo:snapshot-view", () => bridge.snapshotView());
  handle("halo:list-resources", () => bridge.listResources());

  /* ---------------- workspace & preview ---------------- */

  const isInsideProject = (p) => isInsideWorkspace(bridge.cwd || process.cwd(), p);

  const IGNORE = new Set(["node_modules", ".git", "dist", "build", "out", ".next",
    ".nuxt", ".cache", "coverage", "__pycache__", ".venv", "venv", "target", ".idea"]);
  const IGNORE_SEG = new RegExp("(^|[/\\\\])(" + [...IGNORE].join("|") + ")([/\\\\]|$)");

  /* 文件树 watcher：项目内文件变化（含外部编辑器修改）时通知渲染层刷新；
   * 失败（EPERM 等）时静默降级 —— 渲染层在工具写入后仍会主动刷新 */
  let treeWatcher = null, treeWatchTimer = null;
  const armTreeWatcher = () => {
    try {
      disarmTreeWatcher();
      const root = bridge.cwd || process.cwd();
      treeWatcher = fs.watch(root, { recursive: true }, (_ev, fname) => {
        const n = String(fname || "").replace(/\\\\/g, "/");
        if (!n || IGNORE_SEG.test(n) || n.split("/").some((seg) => seg.startsWith("."))) return;
        clearTimeout(treeWatchTimer);
        treeWatchTimer = setTimeout(() => emit("halo:tree-changed", {}), LIMITS.TREE_WATCH_DEBOUNCE);
      });
    } catch { treeWatcher = null; }
  };
  const disarmTreeWatcher = () => {
    clearTimeout(treeWatchTimer);
    treeWatchTimer = null;
    try { treeWatcher?.close(); } catch {}
    treeWatcher = null;
  };

  handle("halo:read-tree", async () => {
    armTreeWatcher();
    const root = path.resolve(bridge.cwd || ".");
    let count = 0;
    const walk = async (dir, depth) => {
      if (depth > LIMITS.TREE_DEPTH || count > LIMITS.TREE_CAP) return [];
      let entries = [];
      try { entries = await fs.promises.readdir(dir, { withFileTypes: true }); } catch { return []; }
      entries.sort((a, b) => (a.isDirectory() === b.isDirectory())
        ? a.name.localeCompare(b.name)
        : (a.isDirectory() ? -1 : 1));
      const out = [];
      for (const e of entries) {
        if (count > LIMITS.TREE_CAP) break;
        if (IGNORE.has(e.name) || e.name.startsWith(".")) continue;
        const full = path.join(dir, e.name);
        if (e.isDirectory()) {
          count++;
          out.push({ name: e.name, path: full, dir: true, children: await walk(full, depth + 1) });
        } else {
          count++;
          let size = 0;
          try { size = (await fs.promises.stat(full)).size; } catch {}
          out.push({ name: e.name, path: full, dir: false, size });
        }
      }
      return out;
    };
    return { root, tree: await walk(root, 0), truncated: count > LIMITS.TREE_CAP };
  });

  // 新建文件/文件夹（名称校验 + 限定项目内）
  const VALID_NAME = /^[^\\/:*?"<>|]+$/;
  handle("halo:create-entry", async ({ parent, name, kind }) => {
    const root = path.resolve(bridge.cwd || ".");
    const rel = String(name || "").trim();
    if (!rel || rel === "." || rel === ".." || !VALID_NAME.test(rel)) throw new Error("名称非法（不能包含 \\/:*?\"<>|）");
    const base = parent ? path.resolve(parent) : root;
    if (!isInsideProject(base)) throw new Error("路径超出项目范围");
    const target = path.join(base, rel);
    if (fs.existsSync(target)) throw new Error(`已存在：${rel}`);
    if (kind === "dir") fs.mkdirSync(target);
    else fs.writeFileSync(target, "", { flag: "wx" });
    return { path: target };
  });

  // 删除文件/文件夹（递归 + 限定项目内，禁止删除根目录；异步避免阻塞主进程）
  handle("halo:delete-entry", async ({ target }) => {
    const root = path.resolve(bridge.cwd || ".");
    const abs = path.resolve(bridge.cwd || ".", String(target || ""));
    if (normP(abs) === normP(root)) throw new Error("不能删除项目根目录");
    if (!isInsideProject(abs)) throw new Error("路径超出项目范围");
    if (!fs.existsSync(abs)) throw new Error("目标不存在");
    await fs.promises.rm(abs, { recursive: true });
    return { deleted: abs };
  });

  handle("halo:document-preview", async ({ file, page }) => {
    const abs = path.resolve(bridge.cwd || ".", file);
    if (!isInsideProject(abs)) throw new Error("路径超出项目范围");
    return previewDocument(abs, page);
  });

  handle("halo:copy-image", async (file) => {
    if(typeof file !== 'string') throw Error('图片路径无效');
    const abs=path.resolve(bridge.cwd || '.',file);
    if(!isInsideProject(abs)) throw Error('路径超出项目范围');
    if(!/\.(png|jpe?g|webp|gif|bmp)$/i.test(abs)) throw Error('该格式暂不支持复制图片');
    const stat=await fs.promises.stat(abs).catch(()=>null);
    if(!stat?.isFile()) throw Error('图片已移动或删除');
    if(stat.size>32*1024*1024) throw Error('图片超过32 MB，无法复制');
    const image=nativeImage.createFromBuffer(await fs.promises.readFile(abs));
    if(image.isEmpty()) throw Error('图片无法解码');
    await clipboard.write([new ClipboardItem({ 'image/png': new Blob([image.toPNG()], {type:'image/png'}) })]);
    return true;
  });

  handle("halo:artifact-files", async (files) => {
    if (!Array.isArray(files) || files.length > 100) throw Error('产物列表无效');
    const found=await Promise.all(files.map(async file=>{
      if(typeof file !== 'string') return null;
      const abs=path.resolve(bridge.cwd || '.',file);
      if(!isInsideProject(abs)) return null;
      const stat=await fs.promises.stat(abs).catch(()=>null);
      return stat?.isFile() ? file : null;
    }));
    return found.filter(Boolean);
  });

  handle("halo:read-file", async (p) => {
    const abs = path.resolve(bridge.cwd || ".", p);
    if (!isInsideProject(abs)) throw new Error("路径超出项目范围");
    return { ...await readPreviewFile(abs, LIMITS.FILE_READ), path: abs };
  });

  handle("halo:open-path", async (p) => {
    const abs = path.resolve(bridge.cwd || ".", p);
    if (!isInsideProject(abs)) throw new Error("路径超出项目范围");
    const error = await shell.openPath(abs);
    if (error) throw new Error(error);
    return true;
  });

  handle("halo:open-external", (url) => {
    if (!/^https:\/\//.test(String(url))) throw new Error("仅允许 https 链接");
    shell.openExternal(String(url));
    return true;
  });

  /* 原生终端池：独立进程、批量输出和背压控制。 */
  const terminals = new TerminalPool((ch, payload) => {
    if (mainWin && !mainWin.isDestroyed()) mainWin.webContents.send(ch, payload);
  });
  app.on("before-quit", () => terminals.dispose());
  handle("halo:pty-start", (opts = {}) => terminals.start({ ...opts, cwd: bridge.cwd || process.cwd() }));
  handle("halo:pty-write", (data) => terminals.write(data));
  handle("halo:pty-resize", (data) => terminals.resize(data));
  handle("halo:pty-ack", (data) => terminals.ack(data));
  handle("halo:pty-kill", (id) => terminals.kill(id));

  handle("halo:pick-project", async (currentPath) => {
    const res = await dialog.showOpenDialog(mainWin, {
      title: "选择项目目录",
      defaultPath: currentPath || store.data.cwd || undefined,
      properties: ["openDirectory"],
    });
    if (res.canceled || !res.filePaths[0]) return null;
    // Selection itself must not restart the bridge. The renderer adds/switches
    // the selected project through the shared session queue below.
    return res.filePaths[0];
  });

  /* 静默切换项目（启动恢复工作区用，无对话框） */
  handle("halo:use-project", (dir) => switchSession(async () => {
    if (!dir || !fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) throw new Error("目录不存在");
    if (normP(dir) !== normP(bridge.cwd)) {
      await bridge.switchProject(dir);
    }
    return true;
  }));

  /* ---------------- 插件与技能（pi 包生态） ---------------- */
  const piHome = () => path.join(app.getPath("home"), ".pi", "agent");
  const readPiSettings = () => {
    try { return JSON.parse(fs.readFileSync(path.join(piHome(), "settings.json"), "utf8")); } catch { return {}; }
  };
  const writePiSettings = (obj) => {
    fs.mkdirSync(piHome(), { recursive: true });
    fs.writeFileSync(path.join(piHome(), "settings.json"), JSON.stringify(obj, null, 2) + "\n");
  };
  // Use the bundled Pi CLI and Electron's Node runtime on every platform.
  const spawnPi = (args) => runPiCommand(args, {
    cwd: bridge.cwd || app.getPath("home"),
    timeout: LIMITS.PKG_TIMEOUT,
  });
  const pkgTypes = (p) => {
    const kws = (p.keywords || []).map((k) => String(k).toLowerCase());
    const hay = [p.name || "", p.description || "", kws.join(" ")].join(" ").toLowerCase();
    const kwHas = (t) => kws.includes("pi-" + t) || kws.includes(t) || kws.includes(t + "s");
    const txtHas = (t) => hay.includes(t);
    const types = [];
    if (kwHas("skill") || (txtHas("skill") && !kws.includes("pi-extension"))) types.push("skill");
    if (kwHas("theme") || txtHas("theme")) types.push("theme");
    if (kwHas("prompt") || txtHas("prompt")) types.push("prompt");
    if (kwHas("extension") || /extension|adapter|toolbar|footer|overlay|dashboard|integrat|workflow/.test(hay)) types.push("extension");
    if (!types.length) types.push(kws.length ? "extension" : "package");
    return types;
  };
  handle("halo:pkg-search", async ({ query = "", from = 0, size = 20, type = "" } = {}) => {
    // 分类用裸关键词下推到 npm 服务端（extension/skill/theme/prompt），与官网分类口径一致
    // （glimpseui 等官网 prompt 包带裸 "prompt" 关键词；pi-prompt 显式关键词只有少数包用）
    const t = ["extension", "skill", "theme", "prompt"].includes(String(type)) ? String(type) : "";
    const text = encodeURIComponent("keywords:pi-package" + (t ? "," + t : "") + (String(query).trim() ? " " + String(query).trim() : ""));
    const res = await fetch(`https://registry.npmjs.org/-/v1/search?text=${text}&size=${size}&from=${from}`);
    if (!res.ok) throw new Error("npm 搜索失败 " + res.status);
    const j = await res.json();
    const items = (j.objects || []).map((o) => {
      const p = o.package || {};
      return {
        name: p.name || "",
        desc: p.description || "",
        version: p.version || "",
        date: p.date || "",
        author: p.publisher?.username || (typeof p.author === "string" ? p.author : p.author?.name) || "",
        repo: p.links?.repository || "",
        homepage: p.links?.homepage || "",
        types: pkgTypes(p),
      };
    });
    return { total: j.total || items.length, items };
  });
  /* 已安装列表 + 版本检测（本地 version vs registry latest → 待更新标记） */
  const collectPkgs = async () => {
    const st = readPiSettings();
    const list = (st.packages || []).map((p) => {
      if (typeof p === "string") {
        const kind = p.startsWith("npm:") ? "npm" : p.startsWith("git:") || /^https?:\/\//.test(p) ? "git" : "本地";
        return { raw: p, source: p, kind, disabled: false };
      }
      const src = p.source || "";
      const kind = src.startsWith("npm:") ? "npm" : src.startsWith("git:") || /^https?:\/\//.test(src) ? "git" : "本地";
      const disabled = ["extensions", "skills", "prompts", "themes"].every((k) => Array.isArray(p[k]) && p[k].length === 0);
      return { raw: src, source: src, kind, disabled };
    });
    await Promise.all(list.filter((p) => p.kind === "npm").map(async (p) => {
      const name = p.source.replace(/^npm:/, "").replace(/@[\w.+-]+$/, (m, off) => (off === 0 || p.source[off - 1] === "/" ? m : ""));
      try {
        const pj = JSON.parse(fs.readFileSync(path.join(piHome(), "npm", "node_modules", name, "package.json"), "utf8"));
        p.version = pj.version || "";
        p.desc = pj.description || "";
        p.homepage = pj.homepage || "";
        p.repo = typeof pj.repository === "string" ? pj.repository : pj.repository?.url || "";
      } catch {}
      try {
        const res = await fetch("https://registry.npmjs.org/" + name.split("/").map(encodeURIComponent).join("/") + "/latest");
        if (res.ok) {
          const j = await res.json();
          p.latest = j.version || "";
          p.desc ||= j.description || "";
          p.homepage ||= j.homepage || "";
          p.repo ||= typeof j.repository === "string" ? j.repository : j.repository?.url || "";
          p.update = !!p.version && !!p.latest && p.version !== p.latest;
        }
      } catch {}
    }));
    for (const p of list.filter((item) => item.kind === "git")) {
      const repo = p.source.replace(/^git:/, "").replace(/^https?:\/\//, "").replace(/(?:\.git)?(?:#.*|@[^/]+)?$/, "");
      if (!/^[\w.-]+\/[\w.-]+\/[\w.-]+$/.test(repo)) continue;
      p.repo = "https://" + repo;
      try {
        const pj = JSON.parse(fs.readFileSync(path.join(piHome(), "git", repo, "package.json"), "utf8"));
        p.desc = pj.description || "";
        p.homepage = pj.homepage || "";
        p.version = pj.version || "";
      } catch {}
    }
    return list;
  };
  handle("halo:pkg-installed", async () => collectPkgs());
  /* 包源白名单：只允许 npm:/git:/https:/本地路径。
   * CLI 参数以数组直接传给内置运行时，不经 shell 解释。 */
  const PKG_SOURCE_RE = /^(npm:[A-Za-z0-9@._~/-]+(@[A-Za-z0-9._-]+)?|git:[^\s"'&|;<>()$`\\]+|https?:\/\/[^\s"'&|;<>()$`]+|\.\.?\/[^\s"'&|;<>()$`]+|[a-zA-Z]:\\[^\s"'&|;<>()$`]*)$/;
  const ensureSource = (source) => {
    if (!PKG_SOURCE_RE.test(String(source || ""))) throw new Error("不支持的包源：" + source);
    return source;
  };
  handle("halo:pkg-install", async ({ source }) => {
    ensureSource(source);
    const r = await spawnPi(["install", source]);
    if (!r.ok) throw new Error(r.error || r.output || `退出码 ${r.code}`);
    return { output: r.output };
  });
  handle("halo:pkg-remove", async ({ source }) => {
    ensureSource(source);
    const r = await spawnPi(["remove", source]);
    if (!r.ok) throw new Error(r.error || r.output || `退出码 ${r.code}`);
    return { output: r.output };
  });
  handle("halo:pkg-update", async ({ source }) => {
    ensureSource(source);
    const r = await spawnPi(["update", source]);
    if (!r.ok) throw new Error(r.error || r.output || `退出码 ${r.code}`);
    return { output: r.output };
  });
  /* 一键更新：逐个更新所有待更新包（版本落后的 npm 包，逐个过白名单再执行） */
  handle("halo:pkg-update-all", async () => {
    const list = await collectPkgs();
    const targets = list.filter((p) => p.update);
    const results = [];
    for (const t of targets) {
      try { ensureSource(t.raw); } catch { results.push({ source: t.raw, ok: false, error: "包源不合法，已跳过" }); continue; }
      const r = await spawnPi(["update", t.raw]);
      results.push({ source: t.raw, ok: r.ok, error: r.ok ? undefined : (r.error || r.output || `退出码 ${r.code}`) });
    }
    return { total: targets.length, updated: results.filter((r) => r.ok).map((r) => r.source), failed: results.filter((r) => !r.ok) };
  });
  /* 启用 / 停用：停用 = settings 里该包改为全空 filter 对象（官方过滤机制），启用 = 恢复字符串 */
  handle("halo:pkg-toggle", async ({ raw, on }) => {
    const st = readPiSettings();
    const list = Array.isArray(st.packages) ? st.packages : [];
    const idx = list.findIndex((p) => (typeof p === "string" ? p : p.source) === raw);
    if (idx < 0) throw new Error("未找到该包：" + raw);
    if (on) {
      list[idx] = typeof list[idx] === "string" ? list[idx] : list[idx].source;
    } else {
      const src = typeof list[idx] === "string" ? list[idx] : list[idx].source;
      list[idx] = { source: src, extensions: [], skills: [], prompts: [], themes: [] };
    }
    st.packages = list;
    writePiSettings(st);
    return true;
  });
  handle("halo:projects-list", async () => bridge.projectsList());
  handle("halo:project-switch", ({ cwd }) => switchSession(() => bridge.switchProject(cwd)));
  handle("halo:project-add", ({ dir }) => switchSession(() => bridge.addProject(dir)));
  handle("halo:project-remove", ({ cwd }) => switchSession(() => bridge.removeProject(cwd)));
  handle("halo:agent-list", async () => scanAgents(bridge.cwd));
  handle("halo:agent-default-get", async () => store.data.defaultAgent || "");
  handle("halo:agent-default-set", async ({ name }) => {
    store.set("defaultAgent", name || "");
    return true;
  });

  handle("halo:pkg-reload", async () => {
    await bridge.start(bridge.cwd);
    return true;
  });

  handle("halo:pick-images", async () => {
    const res = await dialog.showOpenDialog(mainWin, {
      title: "附加图片",
      filters: [{ name: "Images", extensions: ["png", "jpg", "jpeg", "webp", "gif"] }],
      properties: ["openFile", "multiSelections"],
    });
    if (res.canceled) return { files: [], skipped: [] };
    const files = [], skipped = [];
    for (const p of res.filePaths) {
      try {
        if (fs.statSync(p).size > LIMITS.IMAGE_PICK) { skipped.push(path.basename(p)); continue; }
        const b = fs.readFileSync(p).toString("base64");
        const ext = path.extname(p).slice(1).toLowerCase();
        const mediaType = ext === "jpg" ? "image/jpeg" : `image/${ext}`;
        files.push({ name: path.basename(p), mediaType, data: b });
      } catch { skipped.push(path.basename(p)); }
    }
    return { files, skipped };
  });

  // window controls
  ipcMain.on("win:minimize", (e) => { if (trustedSender(e)) mainWin?.minimize(); });
  ipcMain.on("win:maximize", (e) => { if (trustedSender(e)) { if (mainWin?.isMaximized()) mainWin.unmaximize(); else mainWin?.maximize(); } });
  ipcMain.on("win:close", (e) => { if (trustedSender(e)) mainWin?.close(); });

  /* ---------------- app lifecycle ---------------- */

  app.on("second-instance", () => {
    const window = mainWin?.isVisible() ? mainWin : splashWin;
    if (window && !window.isDestroyed()) {
      if (window.isMinimized()) window.restore();
      window.focus();
    }
  });

  app.whenReady().then(() => {
    // preview protocol: serve workspace files to the Preview iframe safely
    const MIME = {
      ".html": "text/html", ".htm": "text/html", ".css": "text/css",
      ".js": "text/javascript", ".mjs": "text/javascript", ".json": "application/json",
      ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
      ".gif": "image/gif", ".webp": "image/webp", ".svg": "image/svg+xml",
      ".md": "text/markdown", ".txt": "text/plain", ".mp4": "video/mp4",
      ".webm": "video/webm", ".pdf": "application/pdf",
    };
    protocol.handle("halo-preview", async (request) => {
      try {
        const u = new URL(request.url);
        let p = decodeURIComponent(u.pathname);
        if (process.platform === "win32") p = p.replace(/^\//, "");
        p = path.normalize(p);
        if (!isInsideProject(p)) return new Response("forbidden", { status: 403 });
        const st = await fs.promises.stat(p).catch(() => null);
        if (!st) return new Response("not found", { status: 404 });
        if (!st.isFile()) return new Response("not found", { status: 404 });
        if (/\.(mp4|webm)$/i.test(p)) return videoResponse(request, p, st.size, MIME[path.extname(p).toLowerCase()]);
        if (st.size > LIMITS.PREVIEW) return new Response("too large", { status: 413 });
        const ext = path.extname(p).toLowerCase();
        const buf = await fs.promises.readFile(p);
        const mime = MIME[ext] || "application/octet-stream";
        // 文本类补 charset，避免无 meta 声明的文件乱码
        const ct = /^text\//.test(mime) || /(javascript|json|svg)/.test(mime) ? `${mime}; charset=utf-8` : mime;
        return new Response(buf, { headers: { "content-type": ct, "cache-control": "no-store" } });
      } catch {
        return new Response("not found", { status: 404 });
      }
    });

    createSplash();
    createMainWindow();
    startupWatchdog = setTimeout(() => {
      if (!quitting) void showStartupFailure('界面初始化超过 15 秒，请重试。');
    }, 15000);
  }).catch(error => {
    console.error('[halo] startup failed:', error);
    void showStartupFailure(error);
  });

  app.on("window-all-closed", () => {
    app.quit();
  });
}
